### ISSUE TITLE
Algorithm Milestone

### ISSUE THREAD

**Issue by KyleHu14** [KyleHu14/theta-website#1]
- [x] processSchedule
  - [x]  Finish updateRarities helper function
  - [x] Combine everything into 1 single object and return
- [x] Readjust sort students to work for the object returned by process schedule
- [x] Reformat availableTimes data structure, make it into a list of objects
- [x] Readjust the algorithm to work 
  - [x] Finish step 2 of the algorithm, if the student has more than 1 avail time
